name: easy_responsive
description: "A Flutter package that helps developers create responsive layouts by adjusting dimensions and font sizes dynamically based on screen size and orientation."
version: 0.0.1
repository: "https://github.com/MohamedEssamFouad/easy_responsive"
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
